title: "Mikk Notes"
description: "My thoughts and notes on the things I learn"
baseurl: "/" # the subpath of your site, e.g., /blog
url: "https://blog.mikklemberg.ee" # the base hostname & protocol for your site
permalink: /:title.html

