title: My Jekyll Blog
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog where I share my thoughts and experiences.
baseurl: "/" # the subpath of your site, e.g., /blog
url: "https://blog.mikklemberg.ee" # the base hostname & protocol for your site
permalink: /:title.html

