title: Mikk Lemberg's Blog
description: >- # this means to ignore newlines until "baseurl:"
  My learning log with my thoughts and notes.
baseurl: "/" # the subpath of your site, e.g., /blog
url: "https://blog.mikklemberg.ee" # the base hostname & protocol for your site
permalink: /:title.html

